name: appscrip_chat_component
description: A new Flutter plugin project.
version: 1.0.0
publish_to: none
homepage: https://github.com/appscrip-3embed/flutter_appscrip_chat.git

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  any_link_preview: ^3.0.0
  app_settings: ^5.1.1
  audioplayers: ^6.0.0
  azlistview: ^2.0.0
  cached_network_image: ^3.3.1
  camera: ^0.11.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.2.1+1
  elegant_notification: ^2.1.2
  emoji_picker_flutter: ^2.0.0
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_local_notifications: ^17.1.2
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.1
  gal: ^2.2.3
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  image: ^4.1.2
  image_cropper: ^7.0.5
  image_painter: ^0.7.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  just_audio: ^0.9.34
  mqtt_client: ^10.2.1
  mqtt_helper: ^0.0.7
  open_filex: ^4.3.2
  path: ^1.8.3
  path_provider: ^2.0.13
  pdfx: ^2.6.0
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  plugin_platform_interface: ^2.1.8
  pull_to_refresh: ^2.0.0
  record: ^5.0.4
  scroll_to_index: ^3.0.1
  share_plus: ^9.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.13
  video_compress: ^3.1.2
  video_player: ^2.6.0
  video_trimmer: ^3.0.1
  visibility_detector: ^0.4.0+2

dependency_overrides:
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# objectbox:
#   output_dir:
#     lib: src/data/database
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  plugin:
    platforms:
      android:
        package: com.example.appscrip_chat_component
        pluginClass: ChatComponentPlugin
      ios:
        pluginClass: ChatComponentPlugin
      web:
        pluginClass: ChatComponentWeb
        fileName: appscrip_chat_component_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/background_images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
