name: appscrip_chat_component
description: A new Flutter plugin project.
version: 1.0.0
publish_to: none
homepage: https://github.com/appscrip-3embed/flutter_appscrip_chat.git

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  any_link_preview: ^3.0.0
  azlistview: ^2.0.0
  cached_network_image: ^3.2.3
  camera: ^0.10.3+2
  carousel_slider: ^4.2.1
  device_info_plus: ^8.1.0
  dio: ^4.0.6
  emoji_picker_flutter: ^1.5.4
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.0
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.8.4
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.1
  geocode: ^1.0.2
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_painter: ^0.5.0
  image_picker: ^0.8.7
  internet_connection_checker: ^1.0.0+1
  intl: any
  link_preview_generator: ^1.2.0
  mqtt_client: ^9.8.0
  objectbox: ^1.7.2
  objectbox_flutter_libs: any
  open_filex: ^4.3.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  plugin_platform_interface: ^2.0.2
  pull_to_refresh: ^2.0.0
  record: ^4.4.4
  scroll_to_index: ^3.0.1
  swipe_to: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  video_compress: ^3.1.2
  video_player: ^2.6.0
  video_trimmer: ^2.0.1
  visibility_detector: ^0.4.0+2
  voice_message_package: ^0.0.74
  wechat_assets_picker: ^8.5.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

objectbox:
  output_dir:
    lib: src/data/database
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.appscrip_chat_component
        pluginClass: ChatComponentPlugin
      ios:
        pluginClass: ChatComponentPlugin
      web:
        pluginClass: ChatComponentWeb
        fileName: chat_component_web.dart
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
