name: appscrip_chat_component
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/appscrip-3embed/flutter_appscrip_chat.git

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  cached_network_image: ^3.2.3
  device_info_plus: ^8.1.0
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  intl: ^0.17.0
  mqtt_client: ^9.8.0
  objectbox: ^1.7.2
  objectbox_flutter_libs: any
  path_provider: ^2.0.13
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

objectbox:
  output_dir:
    lib: src/data/database
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.appscrip_chat_component
        pluginClass: ChatComponentPlugin
      ios:
        pluginClass: ChatComponentPlugin
      web:
        pluginClass: ChatComponentWeb
        fileName: chat_component_web.dart
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
