// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/user_details_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8157527465034351236),
      name: 'UserDetailsModel',
      lastPropertyId: const IdUid(6, 8353752879613478819),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8407387851376352520),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5759417634876605002),
            name: 'userId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7923459479280062720),
            name: 'userToken',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2220693976806851767),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2617108935137887670),
            name: 'userName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8353752879613478819),
            name: 'userProfile',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8157527465034351236),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserDetailsModel: EntityDefinition<UserDetailsModel>(
        model: _entities[0],
        toOneRelations: (UserDetailsModel object) => [],
        toManyRelations: (UserDetailsModel object) => {},
        getId: (UserDetailsModel object) => object.id,
        setId: (UserDetailsModel object, int id) {
          object.id = id;
        },
        objectToFB: (UserDetailsModel object, fb.Builder fbb) {
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          final userTokenOffset = object.userToken == null
              ? null
              : fbb.writeString(object.userToken!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final userNameOffset = object.userName == null
              ? null
              : fbb.writeString(object.userName!);
          final userProfileOffset = object.userProfile == null
              ? null
              : fbb.writeString(object.userProfile!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, userIdOffset);
          fbb.addOffset(2, userTokenOffset);
          fbb.addOffset(3, emailOffset);
          fbb.addOffset(4, userNameOffset);
          fbb.addOffset(5, userProfileOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserDetailsModel(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              userToken: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              userName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              userProfile: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserDetailsModel] entity fields to define ObjectBox queries.
class UserDetailsModel_ {
  /// see [UserDetailsModel.id]
  static final id =
      QueryIntegerProperty<UserDetailsModel>(_entities[0].properties[0]);

  /// see [UserDetailsModel.userId]
  static final userId =
      QueryStringProperty<UserDetailsModel>(_entities[0].properties[1]);

  /// see [UserDetailsModel.userToken]
  static final userToken =
      QueryStringProperty<UserDetailsModel>(_entities[0].properties[2]);

  /// see [UserDetailsModel.email]
  static final email =
      QueryStringProperty<UserDetailsModel>(_entities[0].properties[3]);

  /// see [UserDetailsModel.userName]
  static final userName =
      QueryStringProperty<UserDetailsModel>(_entities[0].properties[4]);

  /// see [UserDetailsModel.userProfile]
  static final userProfile =
      QueryStringProperty<UserDetailsModel>(_entities[0].properties[5]);
}
